import { notFound, redirect } from "next/navigation";

import { prisma } from "@/lib/db";
import { getAccount } from "@/lib/session";
import { findProjectBySlug } from "@/lib/slug";
import ContentTable, { type ContentRow } from "@/components/dashboard/ContentTable";
import type { VerifierVerdict } from "@/types/contracts";

export const dynamic = "force-dynamic";

export default async function ArticlesPage({ params }: { params: Promise<{ slug: string }> }) {
  const account = await getAccount();
  if (!account) redirect("/login");
  const { slug } = await params;

  const project = await findProjectBySlug(account.id, slug);
  if (!project) notFound();

  const items = await prisma.contentItem.findMany({
    where: { projectId: project.id, kind: "ARTICLE" },
    orderBy: { updatedAt: "desc" },
    select: {
      id: true, title: true, status: true, kind: true, primaryKeyword: true, sourceRef: true,
      updatedAt: true, publishedUrl: true, metaTitle: true, metaDescription: true, html: true,
      brief: true, verifierVerdict: true, _count: { select: { versions: true } },
    },
  });

  const rows: ContentRow[] = items.map((it) => {
    const brief = (it.brief ?? {}) as { secondaryKeywords?: string[] };
    const v = it.verifierVerdict as unknown as VerifierVerdict | null;
    return {
      id: it.id, title: it.title ?? "Untitled", status: it.status, kind: it.kind,
      primaryKeyword: it.primaryKeyword,
      secondaryKeywords: Array.isArray(brief.secondaryKeywords) ? brief.secondaryKeywords.slice(0, 8) : [],
      sourceRef: it.sourceRef, updatedAt: it.updatedAt.toISOString(), publishedUrl: it.publishedUrl,
      metaTitle: it.metaTitle, metaDescription: it.metaDescription,
      html: it.html ?? "<p class='text-muted-foreground'>(no draft)</p>",
      verifier: v ? { verdict: v.verdict, isSelfCheck: !!v.isSelfCheck } : null,
      versions: it._count.versions || 1,
    };
  });

  return (
    <div className="mx-auto max-w-6xl space-y-4">
      <div>
        <h1 className="text-xl font-bold">Articles</h1>
        <p className="text-muted-foreground text-sm">Long-form articles generated by Rankenstein. Click a row to inspect the draft, keywords, and grounding verdict.</p>
      </div>
      {rows.length === 0 ? (
        <div className="bg-card text-muted-foreground rounded-xl border p-8 text-center text-sm">
          No articles yet. Generate a batch with the article path, or check the Products tab for product rewrites.
        </div>
      ) : (
        <ContentTable slug={slug} rows={rows} />
      )}
    </div>
  );
}
