import { notFound, redirect } from "next/navigation";

import { prisma } from "@/lib/db";
import { getAccount } from "@/lib/session";
import ContentTable, { type ContentRow } from "@/components/dashboard/ContentTable";
import type { VerifierVerdict } from "@/types/contracts";

export const dynamic = "force-dynamic";

export default async function ContentPage({ params }: { params: Promise<{ id: string }> }) {
  const account = await getAccount();
  if (!account) redirect("/");
  const { id } = await params;

  const project = await prisma.project.findFirst({ where: { id, accountId: account.id }, select: { id: true } });
  if (!project) notFound();

  const items = await prisma.contentItem.findMany({
    where: { projectId: id },
    orderBy: { updatedAt: "desc" },
    select: {
      id: true, title: true, status: true, kind: true, primaryKeyword: true, sourceRef: true,
      updatedAt: true, publishedUrl: true, metaTitle: true, metaDescription: true, html: true,
      brief: true, verifierVerdict: true, _count: { select: { versions: true } },
    },
  });

  const rows: ContentRow[] = items.map((it) => {
    const brief = (it.brief ?? {}) as { secondaryKeywords?: string[] };
    const v = it.verifierVerdict as unknown as VerifierVerdict | null;
    return {
      id: it.id,
      title: it.title ?? "Untitled",
      status: it.status,
      kind: it.kind,
      primaryKeyword: it.primaryKeyword,
      secondaryKeywords: Array.isArray(brief.secondaryKeywords) ? brief.secondaryKeywords.slice(0, 8) : [],
      sourceRef: it.sourceRef,
      updatedAt: it.updatedAt.toISOString(),
      publishedUrl: it.publishedUrl,
      metaTitle: it.metaTitle,
      metaDescription: it.metaDescription,
      html: it.html ?? "<p class='text-gray-400'>(no draft)</p>",
      verifier: v ? { verdict: v.verdict, isSelfCheck: !!v.isSelfCheck } : null,
      versions: it._count.versions || 1,
    };
  });

  return (
    <div className="mx-auto max-w-6xl space-y-4">
      <div>
        <h1 className="text-xl font-bold">Content</h1>
        <p className="text-muted-foreground text-sm">Pieces generated by Rankenstein. Click a row to inspect the rewrite, keywords, and grounding verdict.</p>
      </div>
      <ContentTable rows={rows} />
    </div>
  );
}
